Search.appendIndex(
    [
                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot",
            "name": "Bot",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003A__call\u0028\u0029",
            "name": "__call",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method___call"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003AarrayToObject\u0028\u0029",
            "name": "arrayToObject",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_arrayToObject"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003AgetBotConf\u0028\u0029",
            "name": "getBotConf",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_getBotConf"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003AgetBotId\u0028\u0029",
            "name": "getBotId",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_getBotId"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003AapiRequest\u0028\u0029",
            "name": "apiRequest",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_apiRequest"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003AgetOffsetStore\u0028\u0029",
            "name": "getOffsetStore",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_getOffsetStore"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003AgetUpdates\u0028\u0029",
            "name": "getUpdates",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_getUpdates"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003AgetUpdatesAndCreateEvents\u0028\u0029",
            "name": "getUpdatesAndCreateEvents",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_getUpdatesAndCreateEvents"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003Aasync\u0028\u0029",
            "name": "async",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_async"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003AcountPendingAsyncRequests\u0028\u0029",
            "name": "countPendingAsyncRequests",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_countPendingAsyncRequests"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003ArunAsyncRequests\u0028\u0029",
            "name": "runAsyncRequests",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#method_runAsyncRequests"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003A\u0024botConf",
            "name": "botConf",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#property_botConf"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003A\u0024offsetStore",
            "name": "offsetStore",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#property_offsetStore"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003A\u0024asyncNextRequest",
            "name": "asyncNextRequest",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#property_asyncNextRequest"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Bot\u003A\u003A\u0024asyncRequest",
            "name": "asyncRequest",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Bot.html#property_asyncRequest"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\BotManager",
            "name": "BotManager",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-BotManager.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\BotManager\u003A\u003AselectBot\u0028\u0029",
            "name": "selectBot",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-BotManager.html#method_selectBot"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\BotManager\u003A\u003AselectBotByHash\u0028\u0029",
            "name": "selectBotByHash",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-BotManager.html#method_selectBotByHash"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\BotManager\u003A\u003AgetBotConf\u0028\u0029",
            "name": "getBotConf",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-BotManager.html#method_getBotConf"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\BotManager\u003A\u003AgetBot\u0028\u0029",
            "name": "getBot",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-BotManager.html#method_getBot"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\BotManager\u003A\u003A\u0024botConf",
            "name": "botConf",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-BotManager.html#property_botConf"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\BotManager\u003A\u003A\u0024bots",
            "name": "bots",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-BotManager.html#property_bots"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\DeleteWebhook",
            "name": "DeleteWebhook",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-DeleteWebhook.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\DeleteWebhook\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-DeleteWebhook.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\DeleteWebhook\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-DeleteWebhook.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\DeleteWebhook\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-DeleteWebhook.html#property_signature"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\DeleteWebhook\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-DeleteWebhook.html#property_description"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates",
            "name": "GetUpdates",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "Command\u0020setup\u0020to\u0020run\u0020before\u0020the\u0020work\u0020loop\u0020starts.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_setUp"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003Awork\u0028\u0029",
            "name": "work",
            "summary": "The\u0020work\u0020to\u0020do\u0020during\u0020the\u0020loop.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_work"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AtearDown\u0028\u0029",
            "name": "tearDown",
            "summary": "Work\u0020to\u0020do\u0020after\u0020the\u0020loop\u0020ends.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_tearDown"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AlistenForSignals\u0028\u0029",
            "name": "listenForSignals",
            "summary": "Listen\u0020for\u0020system\u0020signals.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_listenForSignals"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003Ashutdown\u0028\u0029",
            "name": "shutdown",
            "summary": "Shutdown\u0020gracefully",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_shutdown"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AgetSleep\u0028\u0029",
            "name": "getSleep",
            "summary": "Get\u0020the\u0020amount\u0020of\u0020time\u0020to\u0020sleep\u0020in\u0020seconds.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_getSleep"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003Aline\u0028\u0029",
            "name": "line",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_line"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AgetBatchId\u0028\u0029",
            "name": "getBatchId",
            "summary": "Get\u0020the\u0020batch\u0020id.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_getBatchId"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AprintInfo\u0028\u0029",
            "name": "printInfo",
            "summary": "Print\u0020startup\u0020info\u0020to\u0020the\u0020console.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_printInfo"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024sleep",
            "name": "sleep",
            "summary": "The\u0020number\u0020of\u0020seconds\u0020to\u0020sleep\u0020for.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_sleep"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AshouldContinue\u0028\u0029",
            "name": "shouldContinue",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_shouldContinue"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AshouldRunOnce\u0028\u0029",
            "name": "shouldRunOnce",
            "summary": "Determine\u0020if\u0020the\u0020loop\u0020should\u0020only\u0020run\u0020once.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_shouldRunOnce"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003AshouldRunUntilComplete\u0028\u0029",
            "name": "shouldRunUntilComplete",
            "summary": "Determine\u0020if\u0020the\u0020loop\u0020should\u0020run\u0020until\u0020complete.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_shouldRunUntilComplete"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003Acompleted\u0028\u0029",
            "name": "completed",
            "summary": "Mark\u0020the\u0020work\u0020as\u0020completed.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#method_completed"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_hidden"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_signature"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_description"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024run",
            "name": "run",
            "summary": "Whether\u0020the\u0020loop\u0020should\u0020run.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_run"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024complete",
            "name": "complete",
            "summary": "Whether\u0020the\u0020work\u0020is\u0020complete.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_complete"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024runs",
            "name": "runs",
            "summary": "The\u0020iteration\u0020number.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_runs"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024started",
            "name": "started",
            "summary": "Whether\u0020the\u0020work\u0020has\u0020started\u0020or\u0020not.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_started"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024batchId",
            "name": "batchId",
            "summary": "Unique\u0020id\u0020of\u0020the\u0020current\u0020iteration.",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_batchId"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024bot",
            "name": "bot",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_bot"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\GetUpdates\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-GetUpdates.html#property_username"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi",
            "name": "InstallTgBotApi",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003AconfigExists\u0028\u0029",
            "name": "configExists",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#method_configExists"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003AmigrationExists\u0028\u0029",
            "name": "migrationExists",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#method_migrationExists"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003AlistenerExists\u0028\u0029",
            "name": "listenerExists",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#method_listenerExists"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003AalreadyInstalled\u0028\u0029",
            "name": "alreadyInstalled",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#method_alreadyInstalled"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003Apublish\u0028\u0029",
            "name": "publish",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#method_publish"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003ApublishListener\u0028\u0029",
            "name": "publishListener",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#method_publishListener"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003AremoveDirectory\u0028\u0029",
            "name": "removeDirectory",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#method_removeDirectory"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#property_hidden"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#property_signature"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#property_description"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\InstallTgBotApi\u003A\u003A\u0024reInstall",
            "name": "reInstall",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-InstallTgBotApi.html#property_reInstall"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController",
            "name": "MakeTgBotApiController",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController\u003A\u003AgetStub\u0028\u0029",
            "name": "getStub",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html#method_getStub"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController\u003A\u003AgetDefaultNamespace\u0028\u0029",
            "name": "getDefaultNamespace",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html#method_getDefaultNamespace"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController\u003A\u003AdoOtherOperations\u0028\u0029",
            "name": "doOtherOperations",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html#method_doOtherOperations"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html#property_name"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html#property_signature"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html#property_description"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeTgBotApiController\u003A\u003A\u0024type",
            "name": "type",
            "summary": "The\u0020type\u0020of\u0020class\u0020being\u0020generated.",
            "url": "classes/Serogaq-TgBotApi-Console-MakeTgBotApiController.html#property_type"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener",
            "name": "MakeUpdateProcessingListener",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener\u003A\u003AgetStub\u0028\u0029",
            "name": "getStub",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html#method_getStub"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener\u003A\u003AgetDefaultNamespace\u0028\u0029",
            "name": "getDefaultNamespace",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html#method_getDefaultNamespace"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener\u003A\u003AdoOtherOperations\u0028\u0029",
            "name": "doOtherOperations",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html#method_doOtherOperations"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html#property_hidden"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html#property_name"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html#property_description"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\MakeUpdateProcessingListener\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-MakeUpdateProcessingListener.html#property_type"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\SetWebhook",
            "name": "SetWebhook",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-SetWebhook.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\SetWebhook\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-SetWebhook.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\SetWebhook\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-SetWebhook.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\SetWebhook\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-SetWebhook.html#property_signature"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console\\SetWebhook\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Console-SetWebhook.html#property_description"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Events\\NewUpdateReceived",
            "name": "NewUpdateReceived",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Events-NewUpdateReceived.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Events\\NewUpdateReceived\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020event\u0020instance.",
            "url": "classes/Serogaq-TgBotApi-Events-NewUpdateReceived.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Events\\NewUpdateReceived\u003A\u003A\u0024bot",
            "name": "bot",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Events-NewUpdateReceived.html#property_bot"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Events\\NewUpdateReceived\u003A\u003A\u0024update",
            "name": "update",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Events-NewUpdateReceived.html#property_update"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Events\\NewUpdateReceived\u003A\u003A\u0024updateChannel",
            "name": "updateChannel",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Events-NewUpdateReceived.html#property_updateChannel"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotException",
            "name": "BotException",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotException.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotException.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotManagerConfigException",
            "name": "BotManagerConfigException",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotManagerConfigException.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotManagerConfigException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotManagerConfigException.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotManagerException",
            "name": "BotManagerException",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotManagerException.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotManagerException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotManagerException.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotRequestException",
            "name": "BotRequestException",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotRequestException.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotRequestException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotRequestException.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotUpdateException",
            "name": "BotUpdateException",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotUpdateException.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions\\BotUpdateException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Exceptions-BotUpdateException.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\CallbackQueryUpdate",
            "name": "CallbackQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-CallbackQueryUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\CallbackQueryUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-CallbackQueryUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\ChosenInlineResultUpdate",
            "name": "ChosenInlineResultUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-ChosenInlineResultUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\ChosenInlineResultUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-ChosenInlineResultUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\CommandUpdate",
            "name": "CommandUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-CommandUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\CommandUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-CommandUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\ContactUpdate",
            "name": "ContactUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-ContactUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\ContactUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-ContactUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-Controller.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\Controller\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-Controller.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\Controller\u003A\u003A\u0024bot",
            "name": "bot",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-Controller.html#property_bot"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\Controller\u003A\u003A\u0024update",
            "name": "update",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-Controller.html#property_update"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\Controller\u003A\u003A\u0024updateChannel",
            "name": "updateChannel",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-Controller.html#property_updateChannel"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\EventUpdate",
            "name": "EventUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-EventUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\EventUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-EventUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\GameUpdate",
            "name": "GameUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-GameUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\GameUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-GameUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\InlineQueryUpdate",
            "name": "InlineQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-InlineQueryUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\InlineQueryUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-InlineQueryUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\LocationUpdate",
            "name": "LocationUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-LocationUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\LocationUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-LocationUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\MediaUpdate",
            "name": "MediaUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-MediaUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\MediaUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-MediaUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\OtherUpdate",
            "name": "OtherUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-OtherUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\OtherUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-OtherUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\PreCheckoutQueryUpdate",
            "name": "PreCheckoutQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-PreCheckoutQueryUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\PreCheckoutQueryUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-PreCheckoutQueryUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\StickerUpdate",
            "name": "StickerUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-StickerUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\StickerUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-StickerUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\TextUpdate",
            "name": "TextUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-TextUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\TextUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-TextUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\VenueUpdate",
            "name": "VenueUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-VenueUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates\\VenueUpdate\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-Updates-VenueUpdate.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\WebhookController",
            "name": "WebhookController",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-WebhookController.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\WebhookController\u003A\u003Awebhook\u0028\u0029",
            "name": "webhook",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Http-Controllers-WebhookController.html#method_webhook"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Listeners\\UpdateProcessing",
            "name": "UpdateProcessing",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Listeners-UpdateProcessing.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Listeners\\UpdateProcessing\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020the\u0020event\u0020listener.",
            "url": "classes/Serogaq-TgBotApi-Listeners-UpdateProcessing.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Listeners\\UpdateProcessing\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020event.",
            "url": "classes/Serogaq-TgBotApi-Listeners-UpdateProcessing.html#method_handle"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update",
            "name": "Update",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method___construct"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method___toString"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A__debugInfo\u0028\u0029",
            "name": "__debugInfo",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method___debugInfo"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method___get"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A__isset\u0028\u0029",
            "name": "__isset",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method___isset"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AarrayToObject\u0028\u0029",
            "name": "arrayToObject",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_arrayToObject"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AassignUpdateType\u0028\u0029",
            "name": "assignUpdateType",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_assignUpdateType"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AisUpdateType\u0028\u0029",
            "name": "isUpdateType",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_isUpdateType"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AisUpdateTypes\u0028\u0029",
            "name": "isUpdateTypes",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_isUpdateTypes"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AgetMatches\u0028\u0029",
            "name": "getMatches",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_getMatches"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AtextMatch\u0028\u0029",
            "name": "textMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_textMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AtextRegexpMatch\u0028\u0029",
            "name": "textRegexpMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_textRegexpMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AbuttonMatch\u0028\u0029",
            "name": "buttonMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_buttonMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AbuttonRegexpMatch\u0028\u0029",
            "name": "buttonRegexpMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_buttonRegexpMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AinlineButtonMatch\u0028\u0029",
            "name": "inlineButtonMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_inlineButtonMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AinlineButtonRegexpMatch\u0028\u0029",
            "name": "inlineButtonRegexpMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_inlineButtonRegexpMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AcommandMatch\u0028\u0029",
            "name": "commandMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_commandMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AcommandRegexpMatch\u0028\u0029",
            "name": "commandRegexpMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#method_commandRegexpMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AINTERNAL",
            "name": "INTERNAL",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#constant_INTERNAL"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AWEBHOOK",
            "name": "WEBHOOK",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#constant_WEBHOOK"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003AGETUPDATES",
            "name": "GETUPDATES",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#constant_GETUPDATES"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A\u0024_update",
            "name": "_update",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#property__update"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A\u0024_updateTypes",
            "name": "_updateTypes",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#property__updateTypes"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A\u0024_isMatch",
            "name": "_isMatch",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#property__isMatch"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\Update\u003A\u003A\u0024_matches",
            "name": "_matches",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-Update.html#property__matches"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType",
            "name": "UpdateType",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AMESSAGE",
            "name": "MESSAGE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_MESSAGE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ATEXT",
            "name": "TEXT",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_TEXT"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACOMMAND",
            "name": "COMMAND",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_COMMAND"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACOMMAND_WITHOUT_ARGS",
            "name": "COMMAND_WITHOUT_ARGS",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_COMMAND_WITHOUT_ARGS"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACOMMAND_WITH_ARGS",
            "name": "COMMAND_WITH_ARGS",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_COMMAND_WITH_ARGS"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACOMMAND_WITH_ARGS_SPACE",
            "name": "COMMAND_WITH_ARGS_SPACE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_COMMAND_WITH_ARGS_SPACE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACOMMAND_WITH_ARGS_UNDERSCORE",
            "name": "COMMAND_WITH_ARGS_UNDERSCORE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_COMMAND_WITH_ARGS_UNDERSCORE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AMEDIA",
            "name": "MEDIA",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_MEDIA"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003APHOTO",
            "name": "PHOTO",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_PHOTO"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AVIDEO",
            "name": "VIDEO",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_VIDEO"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AVIDEO_NOTE",
            "name": "VIDEO_NOTE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_VIDEO_NOTE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AVOICE",
            "name": "VOICE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_VOICE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ADOCUMENT",
            "name": "DOCUMENT",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_DOCUMENT"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AGAME",
            "name": "GAME",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_GAME"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACONTACT",
            "name": "CONTACT",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_CONTACT"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ADICE",
            "name": "DICE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_DICE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AVENUE",
            "name": "VENUE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_VENUE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ALOCATION",
            "name": "LOCATION",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_LOCATION"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ASTICKER",
            "name": "STICKER",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_STICKER"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT",
            "name": "EVENT",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_NEW_CHAT_MEMBERS",
            "name": "EVENT_NEW_CHAT_MEMBERS",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_NEW_CHAT_MEMBERS"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_LEFT_CHAT_MEMBER",
            "name": "EVENT_LEFT_CHAT_MEMBER",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_LEFT_CHAT_MEMBER"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_PINNED_MESSAGE",
            "name": "EVENT_PINNED_MESSAGE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_PINNED_MESSAGE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_EDITED_MESSAGE",
            "name": "EVENT_EDITED_MESSAGE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_EDITED_MESSAGE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_EDITED_CHANNEL_POST",
            "name": "EVENT_EDITED_CHANNEL_POST",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_EDITED_CHANNEL_POST"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_CHAT_JOIN_REQUEST",
            "name": "EVENT_CHAT_JOIN_REQUEST",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_CHAT_JOIN_REQUEST"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_CHAT_MIGRATE",
            "name": "EVENT_CHAT_MIGRATE",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_CHAT_MIGRATE"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_FORUM_TOPIC_CREATED",
            "name": "EVENT_FORUM_TOPIC_CREATED",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_FORUM_TOPIC_CREATED"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_FORUM_TOPIC_CLOSED",
            "name": "EVENT_FORUM_TOPIC_CLOSED",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_FORUM_TOPIC_CLOSED"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_FORUM_TOPIC_REOPENED",
            "name": "EVENT_FORUM_TOPIC_REOPENED",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_FORUM_TOPIC_REOPENED"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_BOT_LEFT",
            "name": "EVENT_BOT_LEFT",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_BOT_LEFT"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_BOT_JOINED",
            "name": "EVENT_BOT_JOINED",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_BOT_JOINED"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_BOT_BLOCKED",
            "name": "EVENT_BOT_BLOCKED",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_BOT_BLOCKED"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_BOT_UNBLOCKED",
            "name": "EVENT_BOT_UNBLOCKED",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_BOT_UNBLOCKED"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_CHANGE_ADMINISTRATOR",
            "name": "EVENT_CHANGE_ADMINISTRATOR",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_CHANGE_ADMINISTRATOR"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_CHANGE_RESTRICTED",
            "name": "EVENT_CHANGE_RESTRICTED",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_CHANGE_RESTRICTED"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AEVENT_CHANGE_KICKED",
            "name": "EVENT_CHANGE_KICKED",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_EVENT_CHANGE_KICKED"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACHANNEL_POST",
            "name": "CHANNEL_POST",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_CHANNEL_POST"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACALLBACK_QUERY",
            "name": "CALLBACK_QUERY",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_CALLBACK_QUERY"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AINLINE_QUERY",
            "name": "INLINE_QUERY",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_INLINE_QUERY"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ACHOSEN_INLINE_RESULT",
            "name": "CHOSEN_INLINE_RESULT",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_CHOSEN_INLINE_RESULT"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003APRE_CHECKOUT_QUERY",
            "name": "PRE_CHECKOUT_QUERY",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_PRE_CHECKOUT_QUERY"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003ASHIPPING_QUERY",
            "name": "SHIPPING_QUERY",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_SHIPPING_QUERY"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003APOLL",
            "name": "POLL",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_POLL"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003APOLL_ANSWER",
            "name": "POLL_ANSWER",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_POLL_ANSWER"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects\\UpdateType\u003A\u003AOTHER",
            "name": "OTHER",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Objects-UpdateType.html#constant_OTHER"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Providers\\EventServiceProvider",
            "name": "EventServiceProvider",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Providers-EventServiceProvider.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Providers\\EventServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020events\u0020for\u0020your\u0020application.",
            "url": "classes/Serogaq-TgBotApi-Providers-EventServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Providers\\EventServiceProvider\u003A\u003A\u0024listen",
            "name": "listen",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Providers-EventServiceProvider.html#property_listen"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\TgBotApiFacade",
            "name": "TgBotApiFacade",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-TgBotApiFacade.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\TgBotApiFacade\u003A\u003AgetFacadeAccessor\u0028\u0029",
            "name": "getFacadeAccessor",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-TgBotApiFacade.html#method_getFacadeAccessor"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\TgBotApiServiceProvider",
            "name": "TgBotApiServiceProvider",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-TgBotApiServiceProvider.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\TgBotApiServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020the\u0020application\u0020services.",
            "url": "classes/Serogaq-TgBotApi-TgBotApiServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\TgBotApiServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020the\u0020application\u0020services.",
            "url": "classes/Serogaq-TgBotApi-TgBotApiServiceProvider.html#method_register"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingCallbackQueryUpdate",
            "name": "HandlingCallbackQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingCallbackQueryUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingCallbackQueryUpdate\u003A\u003AhandleCallbackQueryUpdate\u0028\u0029",
            "name": "handleCallbackQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingCallbackQueryUpdate.html#method_handleCallbackQueryUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingChosenInlineResultUpdate",
            "name": "HandlingChosenInlineResultUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingChosenInlineResultUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingChosenInlineResultUpdate\u003A\u003AhandleChosenInlineResultUpdate\u0028\u0029",
            "name": "handleChosenInlineResultUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingChosenInlineResultUpdate.html#method_handleChosenInlineResultUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingCommandUpdate",
            "name": "HandlingCommandUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingCommandUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingCommandUpdate\u003A\u003AhandleCommandUpdate\u0028\u0029",
            "name": "handleCommandUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingCommandUpdate.html#method_handleCommandUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingContactUpdate",
            "name": "HandlingContactUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingContactUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingContactUpdate\u003A\u003AhandleContactUpdate\u0028\u0029",
            "name": "handleContactUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingContactUpdate.html#method_handleContactUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingEventUpdate",
            "name": "HandlingEventUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingEventUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingEventUpdate\u003A\u003AhandleEventUpdate\u0028\u0029",
            "name": "handleEventUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingEventUpdate.html#method_handleEventUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingGameUpdate",
            "name": "HandlingGameUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingGameUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingGameUpdate\u003A\u003AhandleGameUpdate\u0028\u0029",
            "name": "handleGameUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingGameUpdate.html#method_handleGameUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingInlineQueryUpdate",
            "name": "HandlingInlineQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingInlineQueryUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingInlineQueryUpdate\u003A\u003AhandleInlineQueryUpdate\u0028\u0029",
            "name": "handleInlineQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingInlineQueryUpdate.html#method_handleInlineQueryUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingLocationUpdate",
            "name": "HandlingLocationUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingLocationUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingLocationUpdate\u003A\u003AhandleLocationUpdate\u0028\u0029",
            "name": "handleLocationUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingLocationUpdate.html#method_handleLocationUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingMediaUpdate",
            "name": "HandlingMediaUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingMediaUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingMediaUpdate\u003A\u003AhandleMediaUpdate\u0028\u0029",
            "name": "handleMediaUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingMediaUpdate.html#method_handleMediaUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingOtherUpdate",
            "name": "HandlingOtherUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingOtherUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingOtherUpdate\u003A\u003AhandleOtherUpdate\u0028\u0029",
            "name": "handleOtherUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingOtherUpdate.html#method_handleOtherUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingPreCheckoutQueryUpdate",
            "name": "HandlingPreCheckoutQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingPreCheckoutQueryUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingPreCheckoutQueryUpdate\u003A\u003AhandlePreCheckoutQueryUpdate\u0028\u0029",
            "name": "handlePreCheckoutQueryUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingPreCheckoutQueryUpdate.html#method_handlePreCheckoutQueryUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingStickerUpdate",
            "name": "HandlingStickerUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingStickerUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingStickerUpdate\u003A\u003AhandleStickerUpdate\u0028\u0029",
            "name": "handleStickerUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingStickerUpdate.html#method_handleStickerUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingTextUpdate",
            "name": "HandlingTextUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingTextUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingTextUpdate\u003A\u003AhandleTextUpdate\u0028\u0029",
            "name": "handleTextUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingTextUpdate.html#method_handleTextUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingVenueUpdate",
            "name": "HandlingVenueUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingVenueUpdate.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\HandlingVenueUpdate\u003A\u003AhandleVenueUpdate\u0028\u0029",
            "name": "handleVenueUpdate",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-HandlingVenueUpdate.html#method_handleVenueUpdate"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\ProcessingInControllers",
            "name": "ProcessingInControllers",
            "summary": "",
            "url": "classes/Serogaq-TgBotApi-Traits-ProcessingInControllers.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits\\ProcessingInControllers\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020event.",
            "url": "classes/Serogaq-TgBotApi-Traits-ProcessingInControllers.html#method_handle"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi",
            "name": "TgBotApi",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi.html"
        },                {
            "fqsen": "\\Serogaq",
            "name": "Serogaq",
            "summary": "",
            "url": "namespaces/serogaq.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-console.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Events",
            "name": "Events",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-events.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-exceptions.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-http-controllers.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-http.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Http\\Controllers\\Updates",
            "name": "Updates",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-http-controllers-updates.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Listeners",
            "name": "Listeners",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-listeners.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Objects",
            "name": "Objects",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-objects.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-providers.html"
        },                {
            "fqsen": "\\Serogaq\\TgBotApi\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/serogaq-tgbotapi-traits.html"
        }            ]
);
