name: Build documentation

on:
  push:
    branches: [ v1 ]
    paths:
      - 'src/**'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker run --rm --volume "$(pwd):/data" phpdoc/phpdoc:3 -vv --target build/docs --cache-folder .phpdoc/cache
      - name: Prepare html
        run: |
          sed -i 's/class="phpdocumentor-topnav__menu">/class="phpdocumentor-topnav__menu" >\n<li class="phpdocumentor-topnav__menu-item -social"><a href="https:\/\/github.com\/phpdocumentor\/phpdocumentor"><span><i class="fab fa-github"><\/i><\/span><\/a><\/li>/g' build/docs/index.html
      - name: Pack docs
        run: sudo tar -czvf docs.tar.gz -C build/docs .
      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: docs.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: github-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_dir: ./public