name: Docs update on GitHub Pages

on:
  push:
    branches:
      - 'v1'
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker run --rm --volume "$(pwd):/data" phpdoc/phpdoc:3 -vv --target build/docs --cache-folder .phpdoc/cache
      - name: Prepare html
        run: |
          sudo find build/docs -type f -name "*.html" -print0 | xargs -0 sudo sed -i 's/class="phpdocumentor-topnav__menu">/class="phpdocumentor-topnav__menu" >\n<li class="phpdocumentor-topnav__menu-item -social"><a target="_blank" href="https:\/\/github.com\/serogaq\/laravel-tgbotapi"><span><i class="fab fa-github"><\/i><\/span><\/a><\/li>/g'
      - name: Pack docs
        run: sudo tar -czvf docs.tar.gz -C build/docs .
      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: docs.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: github-pages
      - name: Unpacking
        run: mkdir -p ./public && tar -xzvf docs.tar.gz -C ./public
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_dir: ./public