name: Run Tests

on:
  push:
    branches:
      - 'v2'
    paths:
      - 'src/**'
      - 'config/**'
      - 'routes/**'
      - 'tests/**'
      - 'composer.json'
      - 'phpunit.xml.dist'
      - 'pint.json'
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**'
      - 'config/**'
      - 'routes/**'
      - 'tests/**'
      - 'composer.json'
      - 'phpunit.xml.dist'
      - 'pint.json'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: ['8.0.2', '8.1', '8.2']
        laravel: ['^8.0', '^9.0']
        stability: [prefer-stable]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}
    env:
      EXTENSIONS: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
      EXT_CACHE_KEY: ext-cache-v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup extensions cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          key: ${{ env.EXT_CACHE_KEY }}

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          coverage: none
          tools: cs2pr

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
      
      - name: Execute tests
        run: vendor/bin/phpunit

      - name: Check .php files for syntax errors
        run: composer php:syntax -- --checkstyle | cs2pr

      - uses: actions/cache@v3
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - name: Check composer dependencies for known security issues
        uses: symfonycorp/security-checker-action@v4
        with:
          lock: ./composer.lock