name: PHP Linting

on: pull_request

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@1.0.0
          with:
            preset: laravel
            verboseMode: true
            configPath: "pint.json"
          