name: Laravel Pint

on:
  push:
    paths:
      - 'src/**'
      - 'routes/**'
      - 'tests/**'
      - 'composer.json'
      - 'pint.json'
  pull_request:
    types: [opened]
    branches: [ v1 ]
    paths:
      - 'src/**'
      - 'routes/**'
      - 'tests/**'
      - 'composer.json'
      - 'pint.json'

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@1.0.0
        with:
          verboseMode: true
          configPath: "pint.json"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[CI] Laravel Pint Coding Style"
          commit_user_name: github-actions[bot] laravel-pint
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
