name: Laravel Pint

on: 
  pull_request:
    branches: [master]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@1.0.0
          with:
            verboseMode: true
            configPath: "pint.json"
        - uses: stefanzweifel/git-auto-commit-action@v4
          commit_message: Laravel Pint Coding Style
          commit_user_name: github-actions[bot] laravel-pint